# Generated by Django 4.2.30 on 2026-08-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField(default=2)),
                ('nombre', models.CharField(max_length=15)),
                ('define', models.TextField()),
            ],
        ),
    ]
