# Generated by Django 4.2.30 on 2026-08-09 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='software',
            options={'verbose_name': 'Herramienta de Software', 'verbose_name_plural': 'Herramientas de Software'},
        ),
        migrations.AlterField(
            model_name='software',
            name='define',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='software',
            name='nombre',
            field=models.CharField(max_length=15, verbose_name='Nombre del Software'),
        ),
    ]
